### ISSUE TITLE
error when using eval_cityscapes_color_1.py

### ISSUE THREAD

**Issue by TheoLiu31** [elnino9ykl/DS-PASS#1]
Hello @ elnino9ykl
When I do evaluation with your code and  pretrained model,  I got the following error:

> $ python eval_swaftnet/eval_cityscapes_color_1.py --datadir /home/theo/Documents/Git/DS-PASS/eval_swaftnet/data/ --subset val --loadDir eval_swaftnet/ --loadWeights eval_swaftnet/model_superbest.pth --loadModel swaftnet.py
> Loading model: eval_swaftnet/swaftnet.py
> Loading weights: eval_swaftnet/eval_swaftnet/model_superbest.pth
> Traceback (most recent call last):
>   File "eval_swaftnet/eval_cityscapes_color_1.py", line 118, in <module>
>     main(parser.parse_args())
>   File "eval_swaftnet/eval_cityscapes_color_1.py", line 44, in main
>     resnet = resnet18(pretrained=True, efficient=False, use_bn=True)
>   File "/home/theo/Documents/Git/DS-PASS/eval_swaftnet/resnet/resnet_single_scale.py", line 232, in resnet18
>     model = ResNet(BasicBlock, [2, 2, 2, 2], use_sppad=use_sppad, split=split, **kwargs)
>   File "/home/theo/Documents/Git/DS-PASS/eval_swaftnet/resnet/resnet_single_scale.py", line 128, in __init__
>     bias=False, use_sppad=use_sppad, split=split)
>   File "/home/theo/Documents/Git/DS-PASS/eval_swaftnet/resnet/sppad.py", line 62, in __init__
>     False, _pair(0), groups, bias)
> TypeError: __init__() missing 1 required positional argument: 'padding_mode'

Can you help me with this error? 
My environment is python 3.6.12, torchvision 0.8.1 and torch 1.7.0

**Comment by elnino9ykl** [comment]
Hi,
  thank you very much for your question.
  This is due to the different PyTorch versions.
  You could add padding_mode='zeros'
